### PR TITLE
Openssl1.1

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
First draft.  There's still a warning about the deprecated `RSA_generate_key()`, but I think that belongs in a separate PR.

**Comment by freddedotme** [comment]
Oh, I was just going to install tarsnap and I assume that's why I get this error?

    lib/crypto/crypto_keys_subr.c:178:23: error: incomplete definition of type 'struct rsa_st'

OpenSSL version:

    OpenSSL 1.1.0c  10 Nov 2016

**Comment by gperciva** [comment]
Yes.  If you're on Debian testing (jessie), you can work around it with:
```
sudo apt-get install libssl1.0-dev
... install Tarsnap...
sudo apt-get install libssl-dev
```

Jessie includes libssl1.0.2, so once it's compiled, tarsnap will the 1.0.2 library.  But you can't have libssl1.0-dev and libssl-dev installed at the same time.  (I don't know why the Debian developers chose to do this, but presumably they have reasons.)

**Comment by cperciva** [comment]
On 12/31/16 12:06, Graham Percival wrote:
> But you can't have libssl1.0-dev and libssl-dev installed at the same
> time. (I don't know why the Debian developers chose to do this, but presumably
> they have reasons.)

I'm guessing that they install header files into the same place?

-- 
Colin Percival
Security Officer Emeritus, FreeBSD | The power to serve
Founder, Tarsnap | www.tarsnap.com | Online backups for the truly paranoid

**Comment by freddedotme** [comment]
I'm on a Macbook (MacOS 10.12.1) so I chose the latest version I could find on their website. I assume I have to downgrade it to 1.0 for now or when is this update supposed to occur?

**Comment by gperciva** [comment]
At the moment, Tarsnap only works with with openssl < 1.1.0.  We are actively looking into what changed in openssl 1.1.0, and how best to support that version; however we cannot give an estimate on when the next release of Tarsnap will be.

File: lib/crypto/crypto_compat.c [hunk 1]
```diff
@@ -26,3 +26,37 @@ crypto_compat_RSA_valid_size(RSA * rsa)
...
+int
+crypto_compat_RSA_import(RSA ** key, BIGNUM * n, BIGNUM * e, BIGNUM * d,
+    BIGNUM * p, BIGNUM * q, BIGNUM * dmp1, BIGNUM * dmq1, BIGNUM * iqmp)
+{
+
+	/* Sanity checks. */
+	assert(key != NULL);
+	assert((n != NULL) && (e != NULL));
+	/* All the private-key-related variables are NULL, or they're not. */
+	assert( ((d == NULL) && (p == NULL) && (q == NULL) && (dmp1 == NULL)
```
Comment (gperciva) [inline lib/crypto/crypto_compat.c]: Not certain what formatting you'd prefer here.  I personally would split up the nesting even more to make it more obvious what's happening, but I suspect you might tell me to remove all semantic spacing entirely.

**Comment by gperciva** [comment]
Updated PR with a different way of organizing the compatibility layer.

File: lib/crypto/crypto_compat.c [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+#include <openssl/rsa.h>
+
+#include "crypto_compat.h"
+
+/**
+ * crypto_compat_RSA_valid_size(rsa):
+ * Check that the RSA ${rsa} has the correct size.
+ */
+int
+crypto_compat_RSA_valid_size(RSA * rsa)
```
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: const?

File: lib/crypto/crypto_compat.c [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+{
+
+	/* Sanity checks. */
+	assert(rsa != NULL);
+	assert(rsa->n != NULL);
+
+	if ((RSA_size(rsa) != 256) || (BN_num_bits(rsa->n) != 2048))
```
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: For such a trivial function, I think I'd write this as
`return ((RSA_size(rsa) == 256) && (BN_num_bits(rsa->n) == 2048));`

File: lib/crypto/crypto_compat.c (hunk 1 above)
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: How about
```
if (d != NULL)
    assert(stuff is not NULL);
else
    assert(stuff is NULL);
```
?  That seems easier to understand than a mess `&&`s and `||`s.

File: lib/crypto/crypto_compat.c [hunk 4]
```diff
@@ -26,3 +26,37 @@ crypto_compat_RSA_valid_size(RSA * rsa)
...
+ */
+int
+crypto_compat_RSA_import(RSA ** key, BIGNUM * n, BIGNUM * e, BIGNUM * d,
+    BIGNUM * p, BIGNUM * q, BIGNUM * dmp1, BIGNUM * dmq1, BIGNUM * iqmp)
+{
+
+	/* Sanity checks. */
+	assert(key != NULL);
+	assert((n != NULL) && (e != NULL));
+	/* All the private-key-related variables are NULL, or they're not. */
```
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: Blank line before comment.

File: lib/crypto/crypto_compat.c [hunk 5]
```diff
@@ -60,3 +60,40 @@ crypto_compat_RSA_import(RSA ** key, BIGNUM * n, BIGNUM * e, BIGNUM * d,
...
+int
+crypto_compat_RSA_export(RSA * key, const BIGNUM ** n, const BIGNUM ** e,
+    const BIGNUM ** d, const BIGNUM ** p, const BIGNUM ** q,
+    const BIGNUM ** dmp1, const BIGNUM ** dmq1, const BIGNUM ** iqmp)
+{
+
+	/* Sanity check. */
+	assert(key != NULL);
+	assert((n != NULL) && (e != NULL));
+	/* All the private-key-related variables are NULL, or they're not. */
```
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: See earlier comments.

File: lib/crypto/crypto_compat.c [hunk 6]
```diff
@@ -62,9 +63,29 @@ crypto_compat_RSA_import(RSA ** key, BIGNUM * n, BIGNUM * e, BIGNUM * d,
 		(*key)->dmq1 = dmq1;
 		(*key)->iqmp = iqmp;
 	}
+#else
+	/* It's ok for d to be NULL here. */
```
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: I'd be inclined to put `if (d == NULL)` first and have two `RSA_set0_key` calls, one of which takes an explicit NULL (with a comment indicating that NULL means we have only the public key).

**Comment by gperciva** [comment]
Rebuilt on top of the new crypto-pre #229 PR.  As usual, the "REBASE" commits are fixing problems that you found.

**Comment by cperciva** [comment]
Is there a way for me to look at this without the commits I've already merged as part of a different PR?  Git is confusing.

**Comment by gperciva** [comment]
OK, I rebased this on top of master.  You've seen the commits without "REBASE" in front of them; the 3 commits with "REBASE" are in response to your comments on the non-REBASE ones.

Or, at this point, perhaps it would be best for me just rewrite the history, and you can look at it from scratch?

File: lib/crypto/crypto_keys_subr.c [hunk 7]
```diff
@@ -208,14 +209,8 @@ crypto_keys_subr_import_RSA_priv(RSA ** key, const uint8_t * buf, size_t buflen)
...
-	(*key)->n = n;
-	(*key)->e = e;
-	(*key)->d = d;
-	(*key)->p = p;
-	(*key)->q = q;
-	(*key)->dmp1 = dmp1;
-	(*key)->dmq1 = dmq1;
-	(*key)->iqmp = iqmp;
+	if (crypto_compat_RSA_import(key, n, e, d, p, q, dmp1, dmq1, iqmp))
+		goto err1;
```
Comment (gperciva) [inline lib/crypto/crypto_keys_subr.c]: Incidently, adding this `err1` fixes a compile warning in current Tarsnap master: At the moment, we skip from err0 to err2 and never use err1, which causes clang to complain about an unused label.

I'm choosing to claim that I intentionally wrote the commits this way, since it minimizes the diffs.  That said, in the future I'll make sure that such things are mentioned in the commit messages, are resolved within a single PR, and I'll enable stricter checking in `.travis.yml`.

**Comment by TimWolla** [comment]
> As usual, the "REBASE" commits are fixing problems that you found.

Tip for your git usage that might save you some time: If you commit using `git commit --fixup <commit hash>` git will automatically create commits that are compatible with the `--autosquash` option of `git rebase --interactive`.

File: lib/crypto/crypto_compat.h [hunk 8]
```diff
@@ -0,0 +1,27 @@
+#ifndef _CRYPTO_COMPAT_H_
+#define _CRYPTO_COMPAT_H_
+
+/**
+ * crypto_compat_RSA_valid_size(rsa):
+ * Check that the RSA key ${rsa} has the correct size.
```
Comment (cperciva) [inline lib/crypto/crypto_compat.h]: This is really a true-or-false question, not a success-or-failure question.

File: lib/crypto/crypto_compat.c [hunk 9]
```diff
@@ -0,0 +1,147 @@
...
+int
+crypto_compat_RSA_valid_size(const RSA * const rsa)
+{
+
+	/* Sanity checks. */
+	assert(rsa != NULL);
+
+#if OPENSSL_VERSION_NUMBER < 0x10100000L
+	assert(rsa->n != NULL);
+	if ((RSA_size(rsa) != 256) || (BN_num_bits(rsa->n) != 2048))
```
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: How about `return ((RSA_size(rsa) != 256) || (BN_num_bits(rsa->n) != 2048));` ?  Or given the name of the function, maybe the negation of that...

File: lib/crypto/crypto_rsa.c [hunk 10]
```diff
@@ -81,7 +82,7 @@ crypto_rsa_sign(int key, const uint8_t * data, size_t len,
 		goto err0;
 
 	/* Make sure the key and signature buffer are the correct size. */
-	if ((RSA_size(rsa) != 256) || (BN_num_bits(rsa->n) != 2048)) {
+	if (crypto_compat_RSA_valid_size(rsa)) {
```
Comment (cperciva) [inline lib/crypto/crypto_rsa.c]: This would make more sense if the function returned nonzero for valid sizes and zero for invalid sizes, so that the code could be `if (!crypto_compat_RSA_valid_size(rsa)) { ...`.  Right now it reads as "if rsa has a valid size, warn that the size is incorrect".

File: lib/crypto/crypto_compat.c (hunk 9 above)
Comment (gperciva) [inline lib/crypto/crypto_compat.c]: I thought that functions were supposed to have a single `return` statement?  Or is this function small enough to be an exception to that rule?

**Comment by gperciva** [comment]
@TimWolla Thanks for the tip about `git commit --fixup`!  I'm not wild about the commit message, though -- I'd feel better if it identified a commit by hash rather than subject, and I'd like to have my own message.  For example, addressing Colin's latest request, I could name the commit either:

```
fixup! crypto_compat: begin, add crypto_compat_RSA_valid_size()
```
or
```
REBASE: invert return values in _RSA_valid_size()
```

I think the second is more informative, so I've opted to use that technique.  Rebasing commits later isn't a big task.  :)

**Comment by gperciva** [comment]
Updated PR

File: lib/crypto/crypto_compat.c (hunk 9 above)
Comment (cperciva) [inline lib/crypto/crypto_compat.c]: Yeah, if the entire content of the function fits into one line, there's no need for the successful-return / failure-return structure.  (And all the more so given that what we're doing here is returning a *value* rather than a *status*.)

**Comment by gperciva** [comment]
Updated PR with two `return` statements.

**Comment by gperciva** [comment]
re OPENSSL_VERSION_NUMBER: it looked ok on Ubuntu 12.04, but I figured we might as well add an `#ifndef` in there just to make sure it's defined.

**Comment by cperciva** [comment]
Looks good.  Please tidy up the commit history, and I'll merge it.

**Comment by gperciva** [comment]
Updated PR with tidied history.

**Comment by gperciva** [comment]
Updated PR with some nitpicks; not ready for merging yet.

**Comment by cperciva** [comment]
Looks good, please clean up the commit history.

**Comment by gperciva** [comment]
Rebased and ready for merging.

Just so you don't get confused, compiling with `clang -Weverything -Werror` with openssl 1.1.0 will still fail with:
```
../lib/crypto/crypto_keys_subr.c:461:10: error: 'RSA_generate_key' is deprecated
      [-Werror,-Wdeprecated-declarations]
        *priv = RSA_generate_key(2048, 65537, NULL, NULL);
                ^
/usr/include/openssl/rsa.h:193:25: note: 'RSA_generate_key' has been explicitly
      marked deprecated here
DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
                        ^
```

Without `-Werror`, it's only a warning (of course).  Adding RSA key generation to the openssl_compat file will come once this PR is merged.

**Comment by cperciva** [comment]
Did you forget to push?  I'm still seeing REBASE commits.

**Comment by gperciva** [comment]
Whoops.  Updated PR for real.
